## Stage 1 ##
FROM node:10 as builder
WORKDIR /app
COPY . .
RUN npm i && npm run prod

## Stage 2 ##
FROM nginx:alpine
WORKDIR /usr/share/nginx/html
RUN rm -rf ./*
COPY --from=builder /app/dist/* .
COPY --from=builder /app/nginx.conf /etc/nginx/conf.d/default.conf
ENTRYPOINT [ "nginx", "-g", "daemon off;" ]
